import os
import sys
import string
import json
import random

# Create output file
with open('products-tsv.sql', 'w', encoding='utf-8') as output_file:
  with open('products-large-tsv.sql', 'w', encoding='utf-8') as output_file_large:

    output_file.write("DROP TABLE IF EXISTS products;\n")
    output_file.write("CREATE TABLE products (id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, name varchar(255) DEFAULT NULL, brand varchar(255) DEFAULT NULL, image varchar(255) DEFAULT NULL, description text DEFAULT NULL, price numeric(10, 2) DEFAULT NULL, sale_price numeric(10, 2) DEFAULT NULL, is_featured boolean DEFAULT NULL, on_sale boolean DEFAULT NULL, on_clearance boolean DEFAULT NULL, price_range varchar(255) DEFAULT NULL, free_shipping boolean DEFAULT NULL, rating numeric(2, 1) DEFAULT NULL, reviews_total integer DEFAULT NULL, sales_total integer DEFAULT NULL, popularity integer DEFAULT NULL, categories jsonb DEFAULT NULL, type varchar(255) DEFAULT NULL, tsv tsvector);\n\n")

    output_file_large.write("DROP TABLE IF EXISTS products;\n")
    output_file_large.write("CREATE TABLE products (id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, name varchar(255) DEFAULT NULL, brand varchar(255) DEFAULT NULL, image varchar(255) DEFAULT NULL, description text DEFAULT NULL, price numeric(10, 2) DEFAULT NULL, sale_price numeric(10, 2) DEFAULT NULL, is_featured boolean DEFAULT NULL, on_sale boolean DEFAULT NULL, on_clearance boolean DEFAULT NULL, price_range varchar(255) DEFAULT NULL, free_shipping boolean DEFAULT NULL, rating numeric(2, 1) DEFAULT NULL, reviews_total integer DEFAULT NULL, sales_total integer DEFAULT NULL, popularity integer DEFAULT NULL, categories jsonb DEFAULT NULL, type varchar(255) DEFAULT NULL, tsv tsvector);\n\n")

    output_file.write("ALTER TABLE products ADD name_prefix char(1) GENERATED ALWAYS AS (LEFT(name, 1)) STORED;\n")
    output_file.write("ALTER TABLE products ADD COLUMN description_tsv TSVECTOR;\n\n")

    output_file_large.write("ALTER TABLE products ADD name_prefix char(1) GENERATED ALWAYS AS (LEFT(name, 1)) STORED;\n")
    output_file_large.write("ALTER TABLE products ADD COLUMN description_tsv TSVECTOR;\n\n")

    output_file.write("CREATE INDEX products_id_idx ON products USING BTREE (id);\n")
    output_file.write("CREATE INDEX products_tsv_idx ON products USING GIN (tsv);\n")
    output_file.write("CREATE INDEX products_brand_idx ON products (lower(brand) varchar_pattern_ops);\n")
    output_file.write("CREATE INDEX products_name_idx ON products (lower(name) varchar_pattern_ops);\n")
    output_file.write("CREATE INDEX products_name_prefix_idx ON products USING BTREE (name_prefix ASC NULLS LAST);\n")
    output_file.write("CREATE INDEX products_price_idx ON products USING BTREE (price ASC NULLS LAST);\n")
    output_file.write("CREATE INDEX products_sale_price_idx ON products USING BTREE (sale_price ASC NULLS LAST);\n")
    output_file.write("CREATE INDEX products_rating_idx ON products USING BTREE (rating DESC NULLS LAST);\n")
    output_file.write("CREATE INDEX products_reviews_total_idx ON products USING BTREE (reviews_total DESC NULLS LAST);\n")
    output_file.write("CREATE INDEX products_sales_total_idx ON products USING BTREE (sales_total DESC NULLS LAST);\n")
    output_file.write("CREATE INDEX products_popularity_idx ON products USING BTREE (popularity DESC NULLS LAST);\n\n")
    output_file.write("CREATE INDEX featured_products_idx ON products USING BTREE (is_featured DESC NULLS LAST, id DESC);\n")

    output_file_large.write("CREATE INDEX products_id_idx ON products USING BTREE (id);\n")
    output_file_large.write("CREATE INDEX products_tsv_idx ON products USING GIN (tsv);\n")
    output_file_large.write("CREATE INDEX products_brand_idx ON products (lower(brand) varchar_pattern_ops);\n")
    output_file_large.write("CREATE INDEX products_name_idx ON products (lower(name) varchar_pattern_ops);\n")
    output_file_large.write("CREATE INDEX products_name_prefix_idx ON products USING BTREE (name_prefix ASC NULLS LAST);\n")
    output_file_large.write("CREATE INDEX products_price_idx ON products USING BTREE (price ASC NULLS LAST);\n")
    output_file_large.write("CREATE INDEX products_sale_price_idx ON products USING BTREE (sale_price ASC NULLS LAST);\n")
    output_file_large.write("CREATE INDEX products_rating_idx ON products USING BTREE (rating DESC NULLS LAST);\n")
    output_file_large.write("CREATE INDEX products_reviews_total_idx ON products USING BTREE (reviews_total DESC NULLS LAST);\n")
    output_file_large.write("CREATE INDEX products_sales_total_idx ON products USING BTREE (sales_total DESC NULLS LAST);\n")
    output_file_large.write("CREATE INDEX products_popularity_idx ON products USING BTREE (popularity DESC NULLS LAST);\n\n")
    output_file_large.write("CREATE INDEX featured_products_idx ON products USING BTREE (is_featured DESC NULLS LAST, id DESC);\n")

    output_file.write("INSERT INTO products (name, brand, image, description, price, sale_price, is_featured, on_sale, on_clearance, price_range, free_shipping, rating, reviews_total, sales_total, popularity, categories, type, tsv)\n")
    output_file.write("VALUES\n")

    output_file_large.write("INSERT INTO products (name, brand, image, description, price, sale_price, is_featured, on_sale, on_clearance, price_range, free_shipping, rating, reviews_total, sales_total, popularity, categories, type, tsv)\n")
    output_file_large.write("VALUES\n")

    # Read input file
    lines = ''
    with open('products.json', 'r', encoding='utf-8') as input_file:
      for line in input_file:
        lines += line.strip()

    data = json.loads(lines)

    for j in range(25):
      i = 0
      for record in data:

        on_sale = False
        price = record['price']
        if random.random() > 0.8:
          sale_price = price - int((random.random() * 10 * price / 100)) - 1
          on_sale = True
        else:
          sale_price = 'NULL'

        is_featured = False if 'image' not in record or record['image'] == None or record['price'] < 70 else random.random() > 0.8
        on_clearance = random.random() > 0.8
        free_shipping = record['free_shipping'] == True

        rating = 0 if 'rating' not in record or record['rating'] == None or record['rating'] == 1 else record['rating'] - 1
        reviews_total = 0 if rating <= 0 else int(random.random() * 10 * (random.random() * 10)) + 1
        popularity = 0 if 'popularity' not in record or record['popularity'] == None else record['popularity']
        sales_total = int(random.random() * 10 * (random.random() * 10))

        categories = 'NULL' if len(record['categories']) == 0 else "'" + json.dumps(record['categories']).replace("'", "''") + "'"

        index = []
        if 'brand' in record and record['brand'] != None:
          index.append("brand:" + record['brand'].replace("'", "''"))
        index.append("on_sale:" + ("1" if on_sale else "0"))
        index.append("on_clearance:" + ("1" if on_clearance else "0"))
        index.append("free_shipping:" + ("1" if free_shipping else "0"))
        if rating > 0:
          index.append("rating:%d" % rating)
        if record['categories'] != None and len(record['categories']) > 0:
          for category in record['categories']:
            if category != None:
              index.append("categories:" + category.replace("'", "''"))
        if record['type'] != None:
          index.append("type:" + record['type'].replace("'", "''"))
        if record['price_range'] != None:
          index.append("price_range:" + record['price_range'])

        tsv = "array_to_tsvector('" + (json.dumps(index)).replace('[', '{').replace(']', '}') + "')" if len(index) > 0 else 'NULL'

        sql = "(%s, %s, %s, %s, %f, %s, %s, %s, %s, '%s', %s, %f, %d, %d, %d, %s, '%s', %s)" % ('NULL' if 'name' not in record or record['name'] == None else "'" + record['name'].replace("'", "''") + "'", 'NULL' if 'brand' not in record else "'" + record['brand'].replace("'", "''") + "'", 'NULL' if 'image' not in record or record['image'] == None else "'" + record['image'].replace("http://", "https://") + "'", 'NULL' if 'description' not in record or record['description'] == None else "'" + record['description'].replace("'", "''") + "'", price, sale_price, is_featured, on_sale, on_clearance, record['price_range'], free_shipping, rating, reviews_total, sales_total, popularity, categories, record['type'].replace("'", "''"), tsv)

        if (j == 0):
          if (i > 0):
            output_file.write(",\n")

          output_file.write(sql)

        if (j > 0 and i > 0):
          output_file_large.write(",\n")

        output_file_large.write(sql)

        i += 1

    output_file.write(";\n\nUPDATE products SET description_tsv = TO_TSVECTOR(description);\n");

    output_file_large.write(";\n\nUPDATE products SET description_tsv = TO_TSVECTOR(description);\n");